"""repaginando tabela de eventos

Revision ID: 2f276bf2fcf6
Revises: 1787724a8d41
Create Date: 2024-02-17 21:44:37.053755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f276bf2fcf6'
down_revision: Union[str, None] = '1787724a8d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    op.add_column('eventos', sa.Column('banner', sa.String(), nullable=True))
    op.add_column('eventos', sa.Column('categoria', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('eventos', sa.Column('onde_comprar_ingressos', sa.String(), nullable=True))
    op.drop_column('eventos', 'foto_url')
    op.drop_column('eventos', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('foto_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('eventos', 'onde_comprar_ingressos')
    op.drop_column('eventos', 'categoria')
    op.drop_column('eventos', 'banner')
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
