"""ajustando campos de controle e evento

Revision ID: 3c5751d528d6
Revises: 2f276bf2fcf6
Create Date: 2024-02-18 16:04:55.433279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c5751d528d6'
down_revision: Union[str, None] = '2f276bf2fcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_controle_carga_id', table_name='controle_carga')
    op.drop_table('controle_carga')
    op.add_column('eventos', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('eventos', sa.Column('data_fim', sa.DateTime(), nullable=True))
    op.add_column('eventos', sa.Column('id_sistema_origem', sa.Integer(), nullable=True))
    op.add_column('eventos', sa.Column('fonte', sa.String(), nullable=True))
    op.add_column('eventos', sa.Column('organizador', sa.String(), nullable=True))
    op.add_column('eventos', sa.Column('gratis', sa.Boolean(), nullable=True))
    op.add_column('eventos', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'atualizado_em')
    op.drop_column('eventos', 'gratis')
    op.drop_column('eventos', 'organizador')
    op.drop_column('eventos', 'fonte')
    op.drop_column('eventos', 'id_sistema_origem')
    op.drop_column('eventos', 'data_fim')
    op.drop_column('eventos', 'endereco')
    op.create_table('controle_carga',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fonte', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inic_exec', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fim_exec', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qtd_src_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qtd_sucesso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ERRO', 'EM_PROGRESSO', 'SUCESSO', name='tipo_categoria'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='controle_carga_pkey')
    )
    op.create_index('ix_controle_carga_id', 'controle_carga', ['id'], unique=False)
    # ### end Alembic commands ###
