"""repaginando usuario

Revision ID: 4bc06a0f8e8c
Revises: d0cd95bbe1f4
Create Date: 2024-02-23 22:42:37.413405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc06a0f8e8c'
down_revision: Union[str, None] = 'd0cd95bbe1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amigos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('amigo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amigo_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'amigo_id')
    )
    op.create_table('usuarios_eventos_foram',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'evento_id')
    )
    op.create_table('usuarios_eventos_querem_ir',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'evento_id')
    )
    op.add_column('usuarios', sa.Column('biografia', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('telefone', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('foto_perfil', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['telefone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'foto_perfil')
    op.drop_column('usuarios', 'telefone')
    op.drop_column('usuarios', 'biografia')
    op.drop_table('usuarios_eventos_querem_ir')
    op.drop_table('usuarios_eventos_foram')
    op.drop_table('amigos')
    # ### end Alembic commands ###
