"""recriando controle de carga

Revision ID: 5a865a844005
Revises: 3c5751d528d6
Create Date: 2024-02-18 16:05:45.702147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a865a844005'
down_revision: Union[str, None] = '3c5751d528d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS tipo_categoria")
    op.create_table('controle_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(), nullable=True),
    sa.Column('inic_exec', sa.DateTime(), nullable=True),
    sa.Column('fim_exec', sa.DateTime(), nullable=True),
    sa.Column('dt_inic', sa.DateTime(), nullable=True),
    sa.Column('dt_fim', sa.DateTime(), nullable=True),
    sa.Column('qtd_src_total', sa.Integer(), nullable=True),
    sa.Column('qtd_sucesso', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ERRO', 'EM_PROGRESSO', 'SUCESSO', name='tipo_categoria'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controle_carga_id'), 'controle_carga', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controle_carga_id'), table_name='controle_carga')
    op.drop_table('controle_carga')
    # ### end Alembic commands ###
