"""add categorias de interesse

Revision ID: d1e05e7e820f
Revises: 4bc06a0f8e8c
Create Date: 2024-02-25 15:14:47.597962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1e05e7e820f'
down_revision: Union[str, None] = '4bc06a0f8e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('categorias_interesse', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'categorias_interesse')
    # ### end Alembic commands ###
