"""criando relacao avaliacao

Revision ID: f5e65e3826a3
Revises: d1e05e7e820f
Create Date: 2024-02-29 23:12:03.694264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e65e3826a3'
down_revision: Union[str, None] = 'd1e05e7e820f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
