name: Aratu Fly.io Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy aratu-api
    runs-on: ubuntu-latest
    concurrency: deploy-group # Ensure only one deploy job runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # Executa o deploy usando flyctl
      - name: Deploy to Fly.io
        run: |
          cd aratu-api
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
